comment:
  image:
    repository: alexgres48/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: alexgres48/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: alexgres48/ui
    tag: latest
  service:
    externalPort: 9292
